---
title: "supp2a-b"
output: html_document
# Written by Neerja Katiyar, Jonah Valenti
---

```{r, echo=FALSE, message=FALSE}
library(dplyr)
library(tidyverse)
library(ggVennDiagram)
library(ggplot2)
library(msigdbr)
library(clusterProfiler)
library(glue)
library(knitr)
library(here)

```

```{r}
knitr::opts_chunk$set(echo = TRUE)
here::i_am("src/enricher_dotplots.Rmd")
knitr::opts_chunk$set(dpi=300,
                      echo=TRUE, warning=FALSE, message=FALSE)
knitr::opts_chunk$set(dev.args=list(bg="transparent"))
knitr::opts_chunk$set(fig.path = glue(here("figs/"), "sg_intersects_"),  dev = c("pdf"))

```

```{r}
# read in data
A673_DE_3days <- read.csv("../tables/A673_condition_treated_results.csv", row.names=1)
CHLA10_DE_3days <- read.csv("../tables/CHLA10_condition_treated_results.csv",row.names=1)
TC32_DE_3days <- read.csv("../tables/TC32_condition_treated_results.csv",row.names=1)

```

```{r}
#extract up/downregulated genes - from here, add new rows when applicable

A673_DE_3days_upreg <- A673_DE_3days %>% filter(log2FoldChange > 0, padj < 0.05)
CHLA10_DE_3days_upreg <- CHLA10_DE_3days %>% filter(log2FoldChange > 0, padj < 0.05)
TC32_DE_3days_upreg <- TC32_DE_3days %>% filter(log2FoldChange > 0, padj < 0.05)

A673_DE_3days_downreg <- A673_DE_3days %>% filter(log2FoldChange < 0, padj < 0.05)
CHLA10_DE_3days_downreg <- CHLA10_DE_3days %>% filter(log2FoldChange < 0, padj < 0.05)
TC32_DE_3days_downreg <- TC32_DE_3days %>% filter(log2FoldChange < 0, padj < 0.05)
```


```{r}
# compile genes

upreg <- list(A673 = rownames(A673_DE_3days_upreg), CHLA10 = rownames(CHLA10_DE_3days_upreg), TC32 = rownames(TC32_DE_3days_upreg))
downreg <- list(A673 = rownames(A673_DE_3days_downreg), CHLA10 = rownames(CHLA10_DE_3days_downreg), TC32 = rownames(TC32_DE_3days_downreg))

A673_upreg = rownames(A673_DE_3days_upreg)
CHLA10_upreg = rownames(CHLA10_DE_3days_upreg)
TC32_upreg = rownames(TC32_DE_3days_upreg)

A673_downreg = rownames(A673_DE_3days_downreg)
CHLA10_downreg = rownames(CHLA10_DE_3days_downreg)
TC32_downreg = rownames(TC32_DE_3days_downreg)

```


```{r}
# compile intersects across groups (i.e. strains)

upreg_intersect_genes <- intersect(intersect(A673_upreg, CHLA10_upreg),TC32_upreg)
downreg_intersect_genes <- intersect(intersect(A673_downreg, CHLA10_downreg),TC32_downreg)

```


```{r}
# define dotplot function

dotplot_custom <- function(data, showCategory, custom_order = NULL, x_range = NULL, plot_width = 6, plot_height = 8) {
  
  # Convert data to DataFrame and subset
  data_df <- as.data.frame(data)
  n <- min(showCategory, nrow(data_df))
  data_df <- data_df[1:n, ]
  
  # Transform data
  data_df$log10_padj <- -log10(data_df$p.adjust)
  data_df$GeneRatio <- sapply(data_df$GeneRatio, function(x) eval(parse(text = x)))
  
  # Apply custom order if provided
  if (!is.null(custom_order)) {
    data_df$Description <- factor(data_df$Description, levels = custom_order)
  } else {
    data_df$Description <- factor(data_df$Description, levels = data_df$Description[order(data_df$log10_padj)])
  }
  
  # Create the plot
  p <- ggplot(data = data_df, aes(x = log10_padj, y = Description,
                                  color = Count, size = GeneRatio)) +
    geom_point() +
    scale_color_gradient(name = "Count", low = "red", high = "blue") +
    scale_size_continuous(name = "GeneRatio", range = c(6, 8), breaks = pretty(data_df$GeneRatio, n = 3)) +
    theme_bw() +
    ylab("") +
    xlab("-log10(p.adjust)") +
    ggtitle("Enrichment analysis") +
    expand_limits(x = 0, y = 0) +
    theme(
      # Adjust the aspect ratio of the plot area
      aspect.ratio = plot_height / plot_width
    )
  
  # Set x-axis range if provided
  if (!is.null(x_range)) {
    p <- p + scale_x_continuous(limits = x_range)
  }
  
  return(p)
}

```


```{r}
# Enrichment analysis step

enrichment_data <- msigdbr(species = "Homo sapiens", category = "H") %>% 
  dplyr::select(gs_name, ensembl_gene)

em_H_upreg <- enricher(upreg_intersect_genes, TERM2GENE=enrichment_data)
em_H_downreg <- enricher(downreg_intersect_genes, TERM2GENE=enrichment_data)


```


```{r}
enrichment_data <- msigdbr(species = "Homo sapiens", category = "C5", subcollection = "GO:BP") %>% 
  dplyr::select(gs_name, ensembl_gene)
goBP_upreg <- enricher(upreg_intersect_genes, TERM2GENE=enrichment_data)
goBP_downreg <- enricher(downreg_intersect_genes, TERM2GENE=enrichment_data)
```


```{r, gobp_upreg, fig.height=12, fig.width=8}
dotplot_custom(goBP_upreg, showCategory=5)

```


```{r}
enrichment_data <- msigdbr(species = "Homo sapiens", category = "C2", subcollection = "CP:REACTOME") %>% 
  dplyr::select(gs_name, ensembl_gene)
react_upreg <- enricher(upreg_intersect_genes, TERM2GENE=enrichment_data)
react_downreg <- enricher(downreg_intersect_genes, TERM2GENE=enrichment_data)
```


```{r, reactome_upreg}
dotplot_custom(react_upreg, showCategory=5)

```

